"""
================================================================================
Phase 2 Test Suite (Corpus Ingestion & Graph Building Verification)
================================================================================

This test script validates Phase 2 graph building components and generated artifacts.

Test Coverage:
    1. Dataset loading (load_pubmedqa_corpus)
    2. Dense passage embeddings integrity (shape, L2-norm, non-NaN)
    3. Sparse BM25s lexical index construction
    4. Hybrid similarity Corpus Graph properties (symmetry, non-negativity, shape)
    5. Artifact file existence and structural validity on disk
"""

import os
import json
import unittest
import numpy as np
import scipy.sparse as sp

from src.build_graph import (
    load_config,
    load_pubmedqa_corpus,
    build_bm25_similarity,
    build_hybrid_corpus_graph
)


class TestPhase2Implementation(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.config_path = "config/default_config.yaml"
        cls.config = load_config(cls.config_path)
        cls.data_dir = cls.config["project"]["data_dir"]
        cls.cache_dir = cls.config["project"]["cache_dir"]

    def test_01_dataset_loading(self):
        """Test PubMedQA corpus loading and field extraction."""
        passages, qrels = load_pubmedqa_corpus(subset="pqa_labeled", max_passages=50)
        self.assertEqual(len(passages), 50, "Failed to load requested passage count.")
        self.assertEqual(len(qrels), 50, "Failed to load requested qrels count.")

        sample_p = passages[0]
        self.assertIn("doc_id", sample_p)
        self.assertIn("text", sample_p)
        self.assertIn("question", sample_p)
        self.assertIn("long_answer", sample_p)
        self.assertIn("final_decision", sample_p)
        self.assertGreater(len(sample_p["text"]), 0, "Passage text is empty.")

    def test_02_bm25_similarity_building(self):
        """Test BM25s lexical sparse matrix properties."""
        passages, _ = load_pubmedqa_corpus(subset="pqa_labeled", max_passages=20)
        bm25_adj = build_bm25_similarity(passages, knn_neighbors=5)
        
        self.assertIsInstance(bm25_adj, sp.csr_matrix)
        self.assertEqual(bm25_adj.shape, (20, 20))
        self.assertGreater(bm25_adj.nnz, 0, "BM25 matrix should have non-zero elements.")
        self.assertTrue((bm25_adj.data >= 0.0).all(), "Scores must be non-negative.")

    def test_03_hybrid_graph_building(self):
        """Test hybrid similarity Corpus Graph symmetry and structure."""
        passages, _ = load_pubmedqa_corpus(subset="pqa_labeled", max_passages=20)
        dummy_embeddings = np.random.randn(20, 128).astype(np.float32)
        dummy_embeddings /= np.linalg.norm(dummy_embeddings, axis=1, keepdims=True)

        graph = build_hybrid_corpus_graph(passages, dummy_embeddings, knn_neighbors=5, similarity_threshold=0.0)
        
        self.assertEqual(graph.shape, (20, 20))
        # Check symmetry A = A^T
        diff = (graph - graph.T).nnz
        self.assertEqual(diff, 0, "Corpus graph must be strictly symmetric.")

    def test_04_serialized_artifacts(self):
        """Test disk artifacts generated by Phase 2."""
        graph_file = os.path.join(self.data_dir, "corpus_graph.npz")
        doc_ids_file = os.path.join(self.data_dir, "doc_ids.json")
        passages_file = os.path.join(self.data_dir, "passages.json")
        qrels_file = os.path.join(self.data_dir, "qrels.json")
        embeddings_file = os.path.join(self.cache_dir, "embeddings.npy")

        for fpath in [graph_file, doc_ids_file, passages_file, qrels_file, embeddings_file]:
            self.assertTrue(os.path.exists(fpath), f"Artifact file '{fpath}' does not exist.")

        # Validate graph matrix
        matrix = sp.load_npz(graph_file)
        self.assertIn(matrix.shape[0], (1000, 62249))
        self.assertGreater(matrix.nnz, 0)

        # Validate embeddings
        embeddings = np.load(embeddings_file)
        self.assertIn(embeddings.shape[0], (1000, 62249))
        self.assertEqual(embeddings.shape[1], 768)
        norms = np.linalg.norm(embeddings, axis=1)
        np.testing.assert_allclose(norms, 1.0, atol=1e-5, err_msg="Embeddings must be L2-normalized.")


if __name__ == "__main__":
    unittest.main()
